permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: pipin Xiao
  email: pingqunnayang@gmail.com
  link: http://zhipingxiao.cn
  weibo: http://weibo.com/zhipingxiao
  github: https://github.com/pingqunnayang

# 站点信息
title: 肖志平的博客
description: My personal blog
url: http://zhipingxiao.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/title.png
favicon: /public/img/title.png

# google analytics 设置
#ga:
# id: UA-54262064-1 
#url: painterlin.com

# disqus 设置
duosuo:
  shortname: pingqunnayang

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Java

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档