# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

url: http:/zhipingxiao.cn

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']



defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: zhipingxiao

description: zhipingxiao's blog
author:
  name: zhipingxiao
  email: nanapingping@163.com
  github: pingqunnayang 
  weibo: zhipingxiao
  pinterest: asd123
  linkedin: asd123
  bio: 痛苦是必然的. 磨烂是可选的.
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
